import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, content-type, x-device-id, x-member-id, x-room-id', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS' };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, 'Content-Type': 'application/json' } });
const error = (message: string, status = 400) => json({ message }, status);
const id = (value: unknown) => String(value ?? '');
const publicMember = (m: any) => ({ _id: m.id, id: m.id, name: m.name, role: m.role, avatar: m.avatar ?? null, deviceId: m.device_id, roomId: m.room_id, isActive: m.is_active, lastActiveAt: m.last_active_at });
const publicRoom = (r: any) => ({ _id: r.id, id: r.id, name: r.name, joinCode: r.join_code, settings: r.settings, createdAt: r.created_at });
const publicExpense = (e: any, memberMap: Record<string, any> = {}) => ({ _id: e.id, id: e.id, roomId: e.room_id, paidBy: memberMap[e.paid_by] ?? e.paid_by, amount: Number(e.amount), description: e.description, category: e.category, participants: (e.participants ?? []).map((p: any) => ({ memberId: memberMap[p.memberId] ?? p.memberId, share: Number(p.share) })), splitType: e.split_type, expenseScope: e.expense_scope, notes: e.notes, receiptUrl: e.receipt_url, source: e.source, clientExpenseId: e.client_expense_id, createdAt: e.created_at });
const recoveryCode = () => { const chars = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ'; const part = () => crypto.getRandomValues(new Uint32Array(4)).reduce((s, n) => s + chars[n % chars.length], ''); return `${part()}-${part()}`; };
const hash = async (value: string) => Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value.trim().toUpperCase())))).map(b => b.toString(16).padStart(2, '0')).join('');
const joinCode = () => `FLAT-${Array.from(crypto.getRandomValues(new Uint8Array(4))).map(b => b.toString(16).padStart(2, '0')).join('').toUpperCase()}`;

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: cors });
  const supabase = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
  const url = new URL(req.url); const path = url.pathname.replace(/^.*\/api/, '') || '/'; const parts = path.split('/').filter(Boolean);
  const body = ['POST', 'PUT', 'PATCH'].includes(req.method) ? await req.json().catch(() => ({})) : {};
  const deviceId = req.headers.get('x-device-id') ?? body.deviceId;
  const memberId = req.headers.get('x-member-id'); const roomHeader = req.headers.get('x-room-id');
  const auth = async () => {
    let q = supabase.from('members').select('*').eq('is_active', true);
    if (memberId) q = q.eq('id', memberId); else if (deviceId && roomHeader) q = q.eq('device_id', deviceId).eq('room_id', roomHeader); else if (deviceId) q = q.eq('device_id', deviceId).order('last_active_at', { ascending: false }).limit(1); else return null;
    const { data } = await q.maybeSingle();
    if (!data) return null;
    await supabase.from('members').update({ last_active_at: new Date().toISOString() }).eq('id', data.id);
    return data;
  };
  const withAuth = async () => { const member = await auth(); return member ? member : null; };
  const membersFor = async (roomId: string) => (await supabase.from('members').select('*').eq('room_id', roomId).eq('is_active', true).order('created_at')).data ?? [];
  const balances = async (roomId: string, currentId: string) => {
    const members = await membersFor(roomId); const map: Record<string, any> = Object.fromEntries(members.map(m => [m.id, { member: publicMember(m), netBalance: 0, owedToMe: 0, iOwe: 0 }]));
    const { data: expenses = [] } = await supabase.from('expenses').select('*').eq('room_id', roomId).eq('expense_scope', 'shared');
    for (const e of expenses) { if (map[e.paid_by]) map[e.paid_by].netBalance += Number(e.amount); for (const p of e.participants ?? []) if (map[p.memberId]) map[p.memberId].netBalance -= Number(p.share); }
    const { data: settlements = [] } = await supabase.from('settlements').select('*').eq('room_id', roomId);
    for (const s of settlements) { if (map[s.from_member]) map[s.from_member].netBalance += Number(s.amount); if (map[s.to_member]) map[s.to_member].netBalance -= Number(s.amount); }
    for (const item of Object.values(map) as any[]) { item.netBalance = Number(item.netBalance.toFixed(2)); item.owedToMe = item.netBalance > .01 ? item.netBalance : 0; item.iOwe = item.netBalance < -.01 ? -item.netBalance : 0; }
    const debtors = Object.values(map).filter((x: any) => x.netBalance < -.01).map((x: any) => ({ ...x })); const creditors = Object.values(map).filter((x: any) => x.netBalance > .01).map((x: any) => ({ ...x })); const plan: any[] = [];
    let d = 0, c = 0; while (d < debtors.length && c < creditors.length) { const amount = Number(Math.min(-debtors[d].netBalance, creditors[c].netBalance).toFixed(2)); plan.push({ from: debtors[d].member, to: creditors[c].member, amount }); debtors[d].netBalance += amount; creditors[c].netBalance -= amount; if (debtors[d].netBalance >= -.01) d++; if (creditors[c].netBalance <= .01) c++; }
    const personal = (await supabase.from('expenses').select('amount').eq('room_id', roomId).eq('paid_by', currentId).eq('expense_scope', 'personal')).data ?? [];
    return { summary: { netBalance: map[currentId]?.netBalance ?? 0, totalIOwe: map[currentId]?.iOwe ?? 0, totalOwedToMe: map[currentId]?.owedToMe ?? 0, totalPersonalSpending: personal.reduce((n, e) => n + Number(e.amount), 0) }, youOwe: plan.filter(p => p.from.id === currentId).map(p => ({ memberId: p.to.id, name: p.to.name, amount: p.amount, member: p.to })), youAreOwed: plan.filter(p => p.to.id === currentId).map(p => ({ memberId: p.from.id, name: p.from.name, amount: p.amount, member: p.from })), allMemberBalances: map, simplifiedSettlementPlan: plan };
  };
  try {
    if (parts[0] === 'health') return json({ status: 'online', app: 'SplitSense Supabase API', timestamp: new Date().toISOString() });
    if (parts[0] === 'rooms' && req.method === 'POST' && parts.length === 1) {
      const name = String(body.name ?? '').trim(), author = String(body.creatorName ?? body.memberName ?? '').trim(); if (!name || !author || !deviceId) return error('Room name, creator name, and device ID are required');
      let room: any; for (let n = 0; n < 3; n++) { const { data, error: dbError } = await supabase.from('rooms').insert({ name, join_code: joinCode() }).select().single(); if (!dbError) { room = data; break; } } if (!room) return error('Unable to create room', 500);
      const code = recoveryCode(); const { data: member, error: memberError } = await supabase.from('members').insert({ room_id: room.id, name: author, role: 'admin', device_id: deviceId, recovery_code_hash: await hash(code), membership_periods: [{ joinedAt: new Date().toISOString(), leftAt: null }] }).select().single(); if (memberError) return error(memberError.message, 500);
      await supabase.from('rooms').update({ created_by: member.id }).eq('id', room.id); return json({ room: publicRoom(room), member: publicMember(member), recoveryCode: code }, 201);
    }
    if (parts[0] === 'rooms' && parts[1] === 'join' && req.method === 'POST') {
      const code = String(body.joinCode ?? '').trim().toUpperCase(); const normalized = code.startsWith('FLAT-') ? code : `FLAT-${code}`; const name = String(body.name ?? body.memberName ?? '').trim(); if (!name || !deviceId) return error('Join code, member name, and device ID are required');
      const { data: room } = await supabase.from('rooms').select('*').eq('join_code', normalized).maybeSingle(); if (!room) return error('Invalid room join code.', 404);
      const byDevice = await supabase.from('members').select('*').eq('room_id', room.id).eq('device_id', deviceId).maybeSingle();
      const byName = byDevice.data ? { data: null } : await supabase.from('members').select('*').eq('room_id', room.id).ilike('name', name).maybeSingle();
      const existing = byDevice.data ?? byName.data; const codeOut = recoveryCode(); let member = existing;
      if (member) { const { data } = await supabase.from('members').update({ name, device_id: deviceId, is_active: true, recovery_code_hash: await hash(codeOut), last_active_at: new Date().toISOString() }).eq('id', member.id).select().single(); member = data; } else { const { data, error: e } = await supabase.from('members').insert({ room_id: room.id, name, device_id: deviceId, recovery_code_hash: await hash(codeOut), membership_periods: [{ joinedAt: new Date().toISOString(), leftAt: null }] }).select().single(); if (e) return error(e.message, 500); member = data; }
      return json({ room: publicRoom(room), member: publicMember(member), members: (await membersFor(room.id)).map(publicMember), recoveryCode: codeOut });
    }
    if (parts[0] === 'rooms' && parts[1] === 'recover' && req.method === 'POST') { if (!body.recoveryCode || !deviceId) return error('Recovery code and device ID are required'); const { data: member } = await supabase.from('members').select('*').eq('recovery_code_hash', await hash(body.recoveryCode)).eq('is_active', true).maybeSingle(); if (!member) return error('Invalid recovery code. Member not found.', 404); await supabase.from('members').update({ device_id: deviceId, last_active_at: new Date().toISOString() }).eq('id', member.id); const { data: room } = await supabase.from('rooms').select('*').eq('id', member.room_id).single(); return json({ room: publicRoom(room), member: publicMember({ ...member, device_id: deviceId }) }); }
    if (parts[0] === 'rooms' && parts[1] === 'preview' && req.method === 'GET') { const query = (parts[2] ?? '').toUpperCase(); const code = query.startsWith('FLAT-') ? query : `FLAT-${query}`; const { data: room } = await supabase.from('rooms').select('*').eq('join_code', code).maybeSingle(); if (!room) return error('Room not found', 404); return json({ room: { ...publicRoom(room), memberCount: (await membersFor(room.id)).length } }); }
    const member = await withAuth(); if (!member) return error('Member not found or inactive in room.', 401);
    if (parts[0] === 'rooms' && req.method === 'GET' && parts[1]) { if (parts[1] !== member.room_id) return error('Unauthorized room access', 403); const { data: room } = await supabase.from('rooms').select('*').eq('id', member.room_id).single(); return json({ room: publicRoom(room), currentMember: publicMember(member), members: (await membersFor(member.room_id)).map(publicMember) }); }
    if (parts[0] === 'rooms' && req.method === 'DELETE' && parts[2] === 'members' && parts[3]) { if (member.role !== 'admin') return error('Only room admins can remove members from the room', 403); if (parts[3] === member.id) return error('Admin cannot remove themselves from the room.'); await supabase.from('members').update({ is_active: false }).eq('id', parts[3]).eq('room_id', member.room_id); return json({ message: 'Member removed successfully from room', members: (await membersFor(member.room_id)).map(publicMember) }); }
    if (parts[0] === 'expenses' && req.method === 'GET' && parts[1] === 'balances') return json(await balances(member.room_id, member.id));
    if (parts[0] === 'expenses' && req.method === 'GET' && parts[1] === 'monthly-summary') { const start = new Date(); start.setDate(1); start.setHours(0,0,0,0); const { data = [] } = await supabase.from('expenses').select('amount, category').eq('room_id', member.room_id).eq('expense_scope', 'shared').gte('created_at', start.toISOString()); const categoryBreakdown: Record<string, number> = {}; for (const e of data) categoryBreakdown[e.category] = (categoryBreakdown[e.category] ?? 0) + Number(e.amount); return json({ monthName: new Intl.DateTimeFormat('en', { month: 'long', year: 'numeric' }).format(new Date()), totalMonthlyShared: data.reduce((n,e) => n + Number(e.amount), 0), categoryBreakdown, expenseCount: data.length }); }
    if (parts[0] === 'expenses' && req.method === 'GET') { let q = supabase.from('expenses').select('*').eq('room_id', member.room_id).order('created_at', { ascending: false }).limit(Math.min(Number(url.searchParams.get('limit') ?? 50), 100)); if (url.searchParams.get('scope') && url.searchParams.get('scope') !== 'all') q = q.eq('expense_scope', url.searchParams.get('scope')!); const { data = [] } = await q; const memberMap = Object.fromEntries((await membersFor(member.room_id)).map(m => [m.id, publicMember(m)])); return json(data.map(e => ({ ...e, _id: e.id, roomId: e.room_id, paidBy: memberMap[e.paid_by], participants: (e.participants ?? []).map((p: any) => ({ memberId: memberMap[p.memberId] ?? { id: p.memberId, _id: p.memberId, name: 'Former member' }, share: Number(p.share) })) }))); }
    if (parts[0] === 'expenses' && req.method === 'POST') { const amount = Number(body.amount); if (!Number.isFinite(amount) || amount <= 0) return error('Valid positive amount required'); const active = await membersFor(member.room_id); const map = Object.fromEntries(active.map(m => [m.id, publicMember(m)])); if (body.clientExpenseId) { const { data: old } = await supabase.from('expenses').select('*').eq('room_id', member.room_id).eq('client_expense_id', body.clientExpenseId).maybeSingle(); if (old) return json({ expense: publicExpense(old, map), balances: await balances(member.room_id, member.id), isDuplicate: true }); } const raw = body.expenseScope === 'personal' ? [{ memberId: member.id, share: amount }] : (body.participants ?? body.splits ?? (body.participantIds?.length ? body.participantIds : active.map(m => m.id))).map((p: any, _: number, a: any[]) => typeof p === 'string' ? ({ memberId: p, share: Number((amount/a.length).toFixed(2)) }) : ({ memberId: p.memberId ?? p.id, share: p.share ?? Number((amount/a.length).toFixed(2)) })); const { data: exp, error: e } = await supabase.from('expenses').insert({ room_id: member.room_id, paid_by: member.id, amount, description: String(body.description ?? 'Shared Expense').trim(), category: body.category ?? 'Other', participants: raw, split_type: body.splitType ?? 'equal', expense_scope: body.expenseScope ?? 'shared', notes: body.notes ?? '', source: body.source ?? 'quick', client_expense_id: body.clientExpenseId ?? null }).select().single(); if (e) return error(e.message, 500); return json({ expense: publicExpense(exp, map), balances: await balances(member.room_id, member.id) }, 201); }
    if (parts[0] === 'expenses' && req.method === 'PUT' && parts[1]) { const { data: exp } = await supabase.from('expenses').select('*').eq('id', parts[1]).maybeSingle(); if (!exp) return error('Expense not found', 404); if (exp.room_id !== member.room_id || (exp.paid_by !== member.id && member.role !== 'admin')) return error('Only the payer or room admin can update this expense', 403); const amount = Number(body.amount); if (!Number.isFinite(amount) || amount < 0) return error('Valid non-negative amount required'); const raw = body.participants?.map((p: any) => ({ memberId: p.memberId ?? p.id ?? p, share: Number(p.share ?? 0) })) ?? exp.participants; const { data: updated, error: updateError } = await supabase.from('expenses').update({ amount, description: body.description ? String(body.description).trim() : exp.description, category: body.category ?? exp.category, participants: raw, split_type: body.splitType ?? exp.split_type, updated_at: new Date().toISOString() }).eq('id', exp.id).select().single(); if (updateError) return error(updateError.message, 500); const map = Object.fromEntries((await membersFor(member.room_id)).map(m => [m.id, publicMember(m)])); return json({ expense: publicExpense(updated, map), balances: await balances(member.room_id, member.id) }); }
    if (parts[0] === 'expenses' && req.method === 'DELETE' && parts[1]) { const { data: exp } = await supabase.from('expenses').select('*').eq('id', parts[1]).maybeSingle(); if (!exp) return error('Expense not found', 404); if (exp.room_id !== member.room_id || (exp.paid_by !== member.id && member.role !== 'admin')) return error('Only the payer or room admin can delete this expense', 403); await supabase.from('expenses').delete().eq('id', exp.id); return json({ message: 'Expense deleted successfully', balances: await balances(member.room_id, member.id) }); }
    if (parts[0] === 'settlements' && req.method === 'GET') { const { data = [] } = await supabase.from('settlements').select('*').eq('room_id', member.room_id).order('created_at', { ascending: false }); const map = Object.fromEntries((await membersFor(member.room_id)).map(m => [m.id, publicMember(m)])); return json(data.map(s => ({ ...s, _id: s.id, fromMember: map[s.from_member], toMember: map[s.to_member] }))); }
    if (parts[0] === 'settlements' && req.method === 'POST') { const amount = Number(body.amount); if (!body.toMemberId || !Number.isFinite(amount) || amount <= 0 || body.toMemberId === member.id) return error('Valid recipient member ID and amount required'); const { data: recipient } = await supabase.from('members').select('id').eq('id', body.toMemberId).eq('room_id', member.room_id).eq('is_active', true).maybeSingle(); if (!recipient) return error('Recipient is not an active room member'); const { data: s, error: e } = await supabase.from('settlements').insert({ room_id: member.room_id, from_member: member.id, to_member: recipient.id, amount, payment_method: body.paymentMethod ?? 'UPI', notes: body.notes ?? '' }).select().single(); if (e) return error(e.message, 500); const all = Object.fromEntries((await membersFor(member.room_id)).map(m => [m.id, publicMember(m)])); return json({ settlement: { ...s, _id: s.id, fromMember: all[s.from_member], toMember: all[s.to_member] }, updatedBalances: await balances(member.room_id, member.id) }, 201); }
    if (parts[0] === 'recurring-expenses' && req.method === 'GET') { const { data = [] } = await supabase.from('recurring_expenses').select('*').eq('room_id', member.room_id).eq('is_active', true).order('next_due_at'); return json(data.map(x => ({ ...x, _id: x.id, roomId: x.room_id, paidBy: x.paid_by, nextDueAt: x.next_due_at }))); }
    if (parts[0] === 'recurring-expenses' && req.method === 'POST') { if (!body.title || !Number(body.amount) || !body.nextDueAt) return error('Title, amount, and next due date are required'); const { data, error: e } = await supabase.from('recurring_expenses').insert({ room_id: member.room_id, title: String(body.title).trim(), amount: Number(body.amount), category: body.category ?? 'Other', paid_by: member.id, participants: body.participantIds ?? [], frequency: body.frequency ?? 'monthly', next_due_at: body.nextDueAt }).select().single(); return e ? error(e.message, 500) : json({ ...data, _id: data.id, roomId: data.room_id, paidBy: member.id, nextDueAt: data.next_due_at }, 201); }
    if (parts[0] === 'recurring-expenses' && req.method === 'DELETE' && parts[1]) { await supabase.from('recurring_expenses').update({ is_active: false }).eq('id', parts[1]).eq('room_id', member.room_id); return json({ message: 'Recurring expense schedule removed' }); }
    return error('Route not found', 404);
  } catch (e) { console.error(e); return error('Internal server error', 500); }
});
