import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import './index.css'
import App from './App.jsx'

// Register the service worker (auto-generated by vite-plugin-pwa + Workbox).
// autoUpdate: the SW updates silently in the background — no user prompt needed.
registerSW({
  onNeedRefresh() {
    // New content available; the SW will update silently on next navigation.
  },
  onOfflineReady() {
    console.log('[FinLit PWA] App is ready for offline use.');
  },
  onRegistered(r) {
    // Periodically check for SW updates every hour (while tab is open)
    r && setInterval(() => r.update(), 60 * 60 * 1000);
  },
  onRegisterError(error) {
    console.warn('[FinLit PWA] Service worker registration failed:', error);
  },
})

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
